baseURL = "http://aliware-os.github.io/nacos1"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Spring Cloud Alibaba Documentation"
theme = "hugo-theme-learn-master"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/aliware-os/nacos1/edit/master/docs/"
  description = "Documentation for Spring Cloud Alibaba"
  author = "Aliware Docs"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Spring Cloud Alibaba"
weight = 1
languageName = "English"
contentDir = "../en"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Roadmap"
url = "roadmaps"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github Repo"
identifier = "ds"
url = "https://github.com/spring-cloud-incubator/spring-cloud-alibaba"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[Languages.zh-cn]
title = "Spring Cloud Alibaba 文档"
weight = 2
languageName = "简体中文"
contentDir = "../zh-cn"

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> 路线图"
url = "roadmaps"
weight = 11

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github 仓库"
identifier = "ds"
url = "https://github.com/spring-cloud-incubator/spring-cloud-alibaba"
weight = 10

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo 官方文档"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20
